export interface SeedGovernorate {
  slug: string;
  name: string;
  lat: number | null;
  lng: number | null;
}

export interface SeedArea {
  slug: string;
  governorateSlug: string;
  name: string;
  lat: number | null;
  lng: number | null;
}

export interface SeedZone {
  slug: string;
  governorateSlug: string;
  areaSlug: string;
  name: string;
  lat: number | null;
  lng: number | null;
}

export const governorates: SeedGovernorate[] = [
  { slug: 'sousse', name: 'سوسة', lat: null, lng: null },
];

export const areas: SeedArea[] = [
  { slug: 'sousse-medina', governorateSlug: 'sousse', name: 'سوسة المدينة', lat: null, lng: null },
  { slug: 'sousse-jawhara', governorateSlug: 'sousse', name: 'سوسة جوهرة', lat: null, lng: null },
  { slug: 'sousse-riadh', governorateSlug: 'sousse', name: 'سوسة الرياض', lat: null, lng: null },
  {
    slug: 'sousse-sidi-abdelhamid',
    governorateSlug: 'sousse',
    name: 'سوسة سيدي عبد الحميد',
    lat: null,
    lng: null,
  },
  { slug: 'hammam-sousse', governorateSlug: 'sousse', name: 'حمام سوسة', lat: null, lng: null },
  { slug: 'akouda', governorateSlug: 'sousse', name: 'أكودة', lat: null, lng: null },
  { slug: 'kalaa-kebira', governorateSlug: 'sousse', name: 'القلعة الكبرى', lat: null, lng: null },
  { slug: 'kalaa-sghira', governorateSlug: 'sousse', name: 'القلعة الصغرى', lat: null, lng: null },
  { slug: 'msaken', governorateSlug: 'sousse', name: 'مساكن', lat: null, lng: null },
  { slug: 'sidi-bouali', governorateSlug: 'sousse', name: 'سيدي بوعلي', lat: null, lng: null },
  { slug: 'sidi-el-hani', governorateSlug: 'sousse', name: 'سيدي الهاني', lat: null, lng: null },
  { slug: 'kondar', governorateSlug: 'sousse', name: 'كندار', lat: null, lng: null },
  { slug: 'hergla', governorateSlug: 'sousse', name: 'هرقلة', lat: null, lng: null },
  { slug: 'enfidha', governorateSlug: 'sousse', name: 'النفيضة', lat: null, lng: null },
  { slug: 'bouficha', governorateSlug: 'sousse', name: 'بوفيشة', lat: null, lng: null },
  {
    slug: 'zaouiet-ksiba-thrayat',
    governorateSlug: 'sousse',
    name: 'الزاوية القصيبة الثريات',
    lat: null,
    lng: null,
  },
];

export const zones: SeedZone[] = [
  // — Sousse Medina —
  {
    slug: 'sousse-medina-old-city',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'المدينة العتيقة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-bab-bahr',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'باب البحر',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-boujaafar',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'بوجعفر',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-boujaafar-touristique',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'منطقة بوجعفر السياحية',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-boulevard',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'شارع الجمهورية',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-mohamed-maarouf',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'محمد معروف',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-hached',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'حي حشاد',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-khadhra',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'الخضراء',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-medina-station',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-medina',
    name: 'المحطة',
    lat: null,
    lng: null,
  },

  // — Sousse Jawhara —
  {
    slug: 'sousse-jawhara-centre',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'جوهرة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-sahloul-1',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'سهلول 1',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-sahloul-2',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'سهلول 2',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-sahloul-3',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'سهلول 3',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-sahloul-4',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'سهلول 4',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-bouhsina',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'بوحسينة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-kalaa',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'حي القلعة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-hached',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'حي الهادي شاكر',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-jawhara-riad',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-jawhara',
    name: 'رياض',
    lat: null,
    lng: null,
  },

  // — Sousse Riadh —
  {
    slug: 'sousse-riadh-centre',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'الرياض',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-riadh-1',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'الرياض 1',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-riadh-2',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'الرياض 2',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-riadh-3',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'الرياض 3',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-riadh-baghdad',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'بغداد',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-riadh-zouhour',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'الزهور',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-riadh-ahd-jadid',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-riadh',
    name: 'العهد الجديد',
    lat: null,
    lng: null,
  },

  // — Sousse Sidi Abdelhamid —
  {
    slug: 'sousse-sidi-abdelhamid-centre',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-sidi-abdelhamid',
    name: 'سيدي عبد الحميد',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-sidi-abdelhamid-industriel',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-sidi-abdelhamid',
    name: 'المنطقة الصناعية سيدي عبد الحميد',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-sidi-abdelhamid-chott',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-sidi-abdelhamid',
    name: 'شط مريم سيدي عبد الحميد',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-sidi-abdelhamid-hammam',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-sidi-abdelhamid',
    name: 'حمام سوسة القديمة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-sidi-abdelhamid-cite-riadh',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-sidi-abdelhamid',
    name: 'حي الرياض',
    lat: null,
    lng: null,
  },
  {
    slug: 'sousse-sidi-abdelhamid-cite-ezzouhour',
    governorateSlug: 'sousse',
    areaSlug: 'sousse-sidi-abdelhamid',
    name: 'حي الزهور',
    lat: null,
    lng: null,
  },

  // — Hammam Sousse —
  {
    slug: 'hammam-sousse-centre',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'حمام سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-ville',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'وسط حمام سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-kantaoui',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'القنطاوي',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-chott-mariam',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'شط مريم',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-corniche',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'الكورنيش',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-boujaafar',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'بوجعفر',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-cite-hached',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'حي حشاد',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-cite-el-ghazali',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'حي الغزالي',
    lat: null,
    lng: null,
  },
  {
    slug: 'hammam-sousse-zone-touristique',
    governorateSlug: 'sousse',
    areaSlug: 'hammam-sousse',
    name: 'المنطقة السياحية',
    lat: null,
    lng: null,
  },

  // — Akouda —
  {
    slug: 'akouda-centre',
    governorateSlug: 'sousse',
    areaSlug: 'akouda',
    name: 'أكودة',
    lat: null,
    lng: null,
  },
  {
    slug: 'akouda-chatt-mariam',
    governorateSlug: 'sousse',
    areaSlug: 'akouda',
    name: 'شط مريم',
    lat: null,
    lng: null,
  },
  {
    slug: 'akouda-beach',
    governorateSlug: 'sousse',
    areaSlug: 'akouda',
    name: 'شاطئ أكودة',
    lat: null,
    lng: null,
  },
  {
    slug: 'akouda-zone-touristique',
    governorateSlug: 'sousse',
    areaSlug: 'akouda',
    name: 'المنطقة السياحية',
    lat: null,
    lng: null,
  },
  {
    slug: 'akouda-el-kantaoui',
    governorateSlug: 'sousse',
    areaSlug: 'akouda',
    name: 'طريق القنطاوي',
    lat: null,
    lng: null,
  },
  {
    slug: 'akouda-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'akouda',
    name: 'المنطقة الصناعية أكودة',
    lat: null,
    lng: null,
  },

  // — Kalaa Kebira —
  {
    slug: 'kalaa-kebira-centre',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'القلعة الكبرى',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-cite-joumhouria',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'حي الجمهورية',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-cite-chouhada',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'حي الشهداء',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-cite-20-mars',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'حي 20 مارس',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-cite-ennahdha',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'حي النهضة',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-cite-el-amal',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-kebira-route-akouda',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-kebira',
    name: 'طريق أكودة',
    lat: null,
    lng: null,
  },

  // — Kalaa Sghira —
  {
    slug: 'kalaa-sghira-centre',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'القلعة الصغرى',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-sghira-cite-takadom',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'حي التقدم',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-sghira-cite-el-amal',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-sghira-cite-ennahdha',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'حي النهضة',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-sghira-station',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'المحطة',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-sghira-zone-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'المنطقة الصناعية',
    lat: null,
    lng: null,
  },
  {
    slug: 'kalaa-sghira-route-msaken',
    governorateSlug: 'sousse',
    areaSlug: 'kalaa-sghira',
    name: 'طريق مساكن',
    lat: null,
    lng: null,
  },

  // — Msaken —
  {
    slug: 'msaken-centre',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'مساكن',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-ville-jadida',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'المدينة الجديدة',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-ouest',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'مساكن الغربية',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-est',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'مساكن الشرقية',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-cite-ennasr',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'حي النصر',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-cite-el-amel',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-cite-ennahdha',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'حي النهضة',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-cite-ezzouhour',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'حي الزهور',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-cite-el-ittihad',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'حي الاتحاد',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-zone-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'المنطقة الصناعية',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'msaken-route-monastir',
    governorateSlug: 'sousse',
    areaSlug: 'msaken',
    name: 'طريق المنستير',
    lat: null,
    lng: null,
  },

  // — Sidi Bouali —
  {
    slug: 'sidi-bouali-centre',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-bouali',
    name: 'سيدي بوعلي',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-bouali-cite-el-amel',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-bouali',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-bouali-cite-ennasr',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-bouali',
    name: 'حي النصر',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-bouali-cite-ennahdha',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-bouali',
    name: 'حي النهضة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-bouali-route-akouda',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-bouali',
    name: 'طريق أكودة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-bouali-zone-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-bouali',
    name: 'المنطقة الصناعية',
    lat: null,
    lng: null,
  },

  // — Sidi El Hani —
  {
    slug: 'sidi-el-hani-centre',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-el-hani',
    name: 'سيدي الهاني',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-el-hani-el-borj',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-el-hani',
    name: 'البرج',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-el-hani-el-kalaa',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-el-hani',
    name: 'القلعة',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-el-hani-route-msaken',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-el-hani',
    name: 'طريق مساكن',
    lat: null,
    lng: null,
  },
  {
    slug: 'sidi-el-hani-zone-rurale',
    governorateSlug: 'sousse',
    areaSlug: 'sidi-el-hani',
    name: 'المناطق الريفية',
    lat: null,
    lng: null,
  },

  // — Kondar —
  {
    slug: 'kondar-centre',
    governorateSlug: 'sousse',
    areaSlug: 'kondar',
    name: 'كندار',
    lat: null,
    lng: null,
  },
  {
    slug: 'kondar-cite-el-amel',
    governorateSlug: 'sousse',
    areaSlug: 'kondar',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'kondar-cite-ennasr',
    governorateSlug: 'sousse',
    areaSlug: 'kondar',
    name: 'حي النصر',
    lat: null,
    lng: null,
  },
  {
    slug: 'kondar-zone-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'kondar',
    name: 'المنطقة الصناعية',
    lat: null,
    lng: null,
  },
  {
    slug: 'kondar-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'kondar',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },

  // — Hergla —
  {
    slug: 'hergla-centre',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'هرقلة',
    lat: null,
    lng: null,
  },
  {
    slug: 'hergla-beach',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'شاطئ هرقلة',
    lat: null,
    lng: null,
  },
  {
    slug: 'hergla-port',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'ميناء هرقلة',
    lat: null,
    lng: null,
  },
  {
    slug: 'hergla-corniche',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'الكورنيش',
    lat: null,
    lng: null,
  },
  {
    slug: 'hergla-zone-touristique',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'المنطقة السياحية',
    lat: null,
    lng: null,
  },
  {
    slug: 'hergla-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'hergla-route-enfidha',
    governorateSlug: 'sousse',
    areaSlug: 'hergla',
    name: 'طريق النفيضة',
    lat: null,
    lng: null,
  },

  // — Enfidha —
  {
    slug: 'enfidha-centre',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'النفيضة',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-cite-el-amel',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-cite-ennasr',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'حي النصر',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-cite-ennahdha',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'حي النهضة',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-zone-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'المنطقة الصناعية',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-aeroport',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'مطار النفيضة الحمامات',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'enfidha-route-hammamet',
    governorateSlug: 'sousse',
    areaSlug: 'enfidha',
    name: 'طريق الحمامات',
    lat: null,
    lng: null,
  },

  // — Bouficha —
  {
    slug: 'bouficha-centre',
    governorateSlug: 'sousse',
    areaSlug: 'bouficha',
    name: 'بوفيشة',
    lat: null,
    lng: null,
  },
  {
    slug: 'bouficha-cite-el-amel',
    governorateSlug: 'sousse',
    areaSlug: 'bouficha',
    name: 'حي الأمل',
    lat: null,
    lng: null,
  },
  {
    slug: 'bouficha-cite-ennasr',
    governorateSlug: 'sousse',
    areaSlug: 'bouficha',
    name: 'حي النصر',
    lat: null,
    lng: null,
  },
  {
    slug: 'bouficha-zone-industrielle',
    governorateSlug: 'sousse',
    areaSlug: 'bouficha',
    name: 'المنطقة الصناعية',
    lat: null,
    lng: null,
  },
  {
    slug: 'bouficha-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'bouficha',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'bouficha-route-hammamet',
    governorateSlug: 'sousse',
    areaSlug: 'bouficha',
    name: 'طريق الحمامات',
    lat: null,
    lng: null,
  },

  // — Zaouiet Ksiba Thrayat —
  {
    slug: 'zaouiet-ksiba-thrayat-centre',
    governorateSlug: 'sousse',
    areaSlug: 'zaouiet-ksiba-thrayat',
    name: 'الزاوية القصيبة الثريات',
    lat: null,
    lng: null,
  },
  {
    slug: 'zaouiet-ksiba',
    governorateSlug: 'sousse',
    areaSlug: 'zaouiet-ksiba-thrayat',
    name: 'القصيبة',
    lat: null,
    lng: null,
  },
  {
    slug: 'thrayat',
    governorateSlug: 'sousse',
    areaSlug: 'zaouiet-ksiba-thrayat',
    name: 'الثريات',
    lat: null,
    lng: null,
  },
  {
    slug: 'zaouiet',
    governorateSlug: 'sousse',
    areaSlug: 'zaouiet-ksiba-thrayat',
    name: 'الزاوية',
    lat: null,
    lng: null,
  },
  {
    slug: 'zaouiet-ksiba-thrayat-route-sousse',
    governorateSlug: 'sousse',
    areaSlug: 'zaouiet-ksiba-thrayat',
    name: 'طريق سوسة',
    lat: null,
    lng: null,
  },
  {
    slug: 'zaouiet-ksiba-thrayat-zone-rurale',
    governorateSlug: 'sousse',
    areaSlug: 'zaouiet-ksiba-thrayat',
    name: 'المناطق الريفية',
    lat: null,
    lng: null,
  },
];

// — In-memory helpers used by other modules for quick lookups —

export function getGovernorateById(slug: string): SeedGovernorate | undefined {
  return governorates.find((g) => g.slug === slug);
}

export function getAreaById(governorateSlug: string, areaSlug: string): SeedArea | undefined {
  return areas.find((a) => a.governorateSlug === governorateSlug && a.slug === areaSlug);
}

export function getZoneById(
  governorateSlug: string,
  areaSlug: string,
  zoneSlug: string,
): SeedZone | undefined {
  return zones.find(
    (z) => z.governorateSlug === governorateSlug && z.areaSlug === areaSlug && z.slug === zoneSlug,
  );
}
